image: node:lts-alpine

stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy:
  image: docker:19.03.12
  stage: deploy
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/visualitgroup/front/app:latest .
    - docker push $CI_REGISTRY/visualitgroup/front/app:latest
